-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 17:58:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_temas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `musica` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_sobre_banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_sobre_banda` (
  `instrumentos` VARCHAR(255) NOT NULL,
  `id_sobre_banda` BIGINT(20) NOT NULL,
  `tipo_musical` VARCHAR(45) NOT NULL,
  `shows` TINYINT NOT NULL,
  `integrantes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sobre_banda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_bandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_bandas` (
  `bandas_preferidas` VARCHAR(255) NOT NULL,
  `id_banda` BIGINT NOT NULL AUTO_INCREMENT,
  `qtds_shows` INT(20) NOT NULL,
  `data_formacao` DATE NOT NULL,
  `msc_maior_sucesso` VARCHAR(255) NOT NULL,
  `fk_sobre_banda` BIGINT NOT NULL,
  `fk_temas` BIGINT NOT NULL,
  PRIMARY KEY (`id_banda`),
  INDEX `fk_sobre_banda_idx` (`fk_sobre_banda` ASC) VISIBLE,
  INDEX `fk_temas_idx` (`fk_temas` ASC) VISIBLE,
  CONSTRAINT `fk_sobre_banda`
    FOREIGN KEY (`fk_sobre_banda`)
    REFERENCES `mydb`.`tb_sobre_banda` (`id_sobre_banda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temas`
    FOREIGN KEY (`fk_temas`)
    REFERENCES `mydb`.`tb_temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
